apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgresql
        image: postgres:16.0-bullseye
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "masterclass100"
        - name: POSTGRES_USER
          value: "masterclass"
        - name: POSTGRES_DB
          value: "sampledb"
